      version: '2'

      services:
        elasticsearch:
          build: elasticsearch/
          ports:
            - "9200:9200"
            - "9300:9300"
          environment:
            ES_JAVA_OPTS: "-Xms1g -Xmx1g"
          user: esuser
          networks:
            - docker_elk
          volumes:
            - $PWD/data/es/:/home/esuser/data  
        logstash:
          build: logstash/
          ports:
            - "5000:5000"
          user: lsuser
          networks:
            - docker_elk
          depends_on:
            - elasticsearch
        kibana:
          build: kibana/
          ports:
            - "5601:5601"
          user: kbuser
          networks:
            - docker_elk
          depends_on:
            - elasticsearch
        nginx:
          build: nginx/
          ports:
            - "8080:80"
          networks:
            - docker_elk
          depends_on:
            - logstash

      networks:
        docker_elk:
          driver: bridge
